-- RETORNA DATA/HORA ATUAL
SELECT CURRENT_TIMESTAMP() AS DATA_ATUAL;

-- EXEMPLO
SELECT CONCAT('O dia e hora atual é: ', CURRENT_TIMESTAMP());

-- SELECIONANDO SOMENTE ANO
SELECT CONCAT('O dia de hoje é: ', DATE_FORMAT(CURRENT_TIMESTAMP(),'%Y') );

-- SELECIONANDO SOMENTE DATA SEM HORA
SELECT CONCAT('O dia de hoje é: ', DATE_FORMAT(CURRENT_TIMESTAMP(),'%d/%m/%Y') );

-- RETORNA O DIA DA SEMANA
SELECT CONCAT('O dia de hoje é: ', DATE_FORMAT(CURRENT_TIMESTAMP(),'%W, %d/%m/%Y') );

-- CONVERTER TIPO DE DADO
-- NUMERO EM TEXTO
SELECT CONVERT(23.3, CHAR);





