-- QUANTIDADE TOTAL 2016
SELECT
	YEAR(NF.DT_VENDA) AS ANO, 
    SUM(INF.QUANTODADE) AS QUANTIDADE 
FROM TB_PRODUTOS PRO
INNER JOIN TB_ITENSNF INF ON PRO.COD_PRODUTO = INF.COD_PRODUTO
INNER JOIN TB_NFS NF ON INF.NUM_NOTA = NF.NUM_NOTA
WHERE YEAR(NF.DT_VENDA) = 2023
GROUP BY YEAR(NF.DT_VENDA);