-- VENDAS DE CLIENTES POR MES
SELECT 
	NF.CPF, 
    DATE_FORMAT(NF.DT_VENDA, '%Y-%m') AS MES_ANO, 
    SUM(INF.QUANTODADE) AS QUANTIDADE_VENDAS 
FROM TB_NFS NF
INNER JOIN TB_ITENSNF INF ON NF.NUM_NOTA = INF.NUM_NOTA
GROUP BY NF.CPF, DATE_FORMAT(NF.DT_VENDA, '%Y-%m');

-- LIMITE DE COMPRA POR CLIENTE
SELECT CPF, NOME, (LIMITE_CREDITO - VOLUME_COMPRA) AS QUANTIDADE_LIMITE
FROM TB_CLIENTES;

--  Exibira: todas as vendas mensais por CPF.
SELECT 
	NF.CPF,
    CLI.NOME, 
    DATE_FORMAT(NF.DT_VENDA, '%Y-%m') AS MES_ANO, 
    SUM(INF.QUANTODADE) AS QUANTIDADE_VENDAS, 
    MAX(CLI.VOLUME_COMPRA) AS QUANTIDADE_LIMITE 
FROM TB_NFS NF
INNER JOIN TB_ITENSNF INF ON NF.NUM_NOTA = INF.NUM_NOTA
INNER JOIN TB_CLIENTES CLI  ON NF.CPF = CLI.CPF
GROUP BY NF.CPF, CLI.NOME, DATE_FORMAT(NF.DT_VENDA, '%Y-%m');

-- Exibira: todas as vendas mensais por CPF, validando as compras.
SELECT 
	X.CPF, 
    X.NOME, 
    X.MES_ANO, 
    X.QUANTIDADE_VENDAS, 
    X.QUANTIDADE_LIMITE,
	CASE 
		WHEN (X.QUANTIDADE_LIMITE - X.QUANTIDADE_VENDAS) < 0 THEN 'INVÁLIDA'
		ELSE 'VÁLIDA' 
	END AS STATUS_VENDA
FROM (
	SELECT 
		NF.CPF, 
        CLI.NOME, 
        DATE_FORMAT(NF.DT_VENDA, '%Y-%m') AS MES_ANO, 
		SUM(INF.QUANTODADE) AS QUANTIDADE_VENDAS , 
		MAX(CLI.VOLUME_COMPRA) AS QUANTIDADE_LIMITE 
    FROM TB_NFS NF
	INNER JOIN TB_ITENSNF INF ON NF.NUM_NOTA = INF.NUM_NOTA
	INNER JOIN TB_CLIENTES CLI ON NF.CPF = CLI.CPF
	GROUP BY NF.CPF, CLI.NOME, DATE_FORMAT(NF.DT_VENDA, '%Y-%m')
    ) X;