CREATE DATABASE SUPERMERCADO;

USE SUPERMERCADO;

CREATE TABLE TB_CLIENTES (
	CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(50),
    ENDERECO VARCHAR(50),
    BAIRRO VARCHAR(25),
    CIDADE VARCHAR(25),
    ESTADO VARCHAR(25),
    CEP INT,
    IDADE INT,
    SEXO VARCHAR(1),
    LIMITE_CREDITO DOUBLE,
    VOLUME_COMPRA DOUBLE,
    PRIMEIRA_COMPRA BOOLEAN
);

CREATE TABLE TB_VENDEDORES (
	MATRICULA INT PRIMARY KEY,
    NOME VARCHAR(50),
    COMISSAO DOUBLE,
    DT_ADMISSAO DATE,
    FERIAS BOOLEAN,
    BAIRRO VARCHAR(25)
);

CREATE TABLE TB_PRODUTOS (
	COD_PRODUTO INT PRIMARY KEY,
    PRODUTO VARCHAR(50),
    PRECO DOUBLE
);

CREATE TABLE TB_NFS (
	NUM_NOTA INT PRIMARY KEY,
    DT_VENDA DATE,
    CPF VARCHAR(11),
    MATRICULA INT,
    IMPOSTO DOUBLE,
    FOREIGN KEY (CPF) REFERENCES TB_CLIENTES (CPF),
    FOREIGN KEY (MATRICULA) REFERENCES TB_VENDEDORES (MATRICULA)
);

CREATE TABLE TB_ITENSNF (
	NUM_NOTA INT,
    COD_PRODUTO INT,
    QUANTODADE INT,
    PRECO DOUBLE,
    FOREIGN KEY (NUM_NOTA) REFERENCES TB_NFS (NUM_NOTA),
    FOREIGN KEY (COD_PRODUTO) REFERENCES TB_PRODUTOS (COD_PRODUTO)
);